name: Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-and-test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with: { bun-version: "1.1.0" }
      - run: bun install --frozen-lockfile
      - run: bun check:format
      - run: bun check
        if: ${{ !cancelled() }}
